---
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPekNDQWlPZ0F3SUJBZ0lVWWVLUVpaUVI5cHRXQm5ZSzJ0dG1nRXQ4M3Rnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xURXJNQ2tHQTFVRUF3d2ljbVZuYVhOMGNua3VaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaApiREFlRncweU5EQTRNamt5TXpBeE1URmFGdzB5TlRBNE1qa3lNekF4TVRGYU1DMHhLekFwQmdOVkJBTU1JbkpsCloybHpkSEo1TG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNneFRvcVdHYWNlVU1pNDdPY1l5SDJrYUd1L1VHTE1QYld6RWJhSW9qNQpJZmhsaG5meWJkdDNHVjMxMmgzZnRLdGhLUC8wc2NheW1MNkY1UlQ4OTRIelEyTUdpZ2NoSnNsTGNtNUNiWXJ6CmpwM2xCa0VQdTd5Y0JxcEsrWENOeWt0Q25BY3FtT0FNdHJDcUR6Mk50OVdUc0JRQnhFL01PbmlqL2hzeS9aUXoKN21JV2FUc2QvRmNhN2sxakowUi9jaEJrS3VzNzNpWHo1TjdwSjF3UzZiNE0zRWltRlJVcFMrRndndGxjc3JuYwpydDczRlJwV3FmcW1NYVIwU2lnNUlvSzFHQXY3bFFvS29mRS9odEk4SmNZekJvbHhFY2c3YitiaTd5TDBaTmc0CjR6K2M1VGI2eWlETmZUQm1PNzdBTFRyYWtacjhuVHUvM0dKTHF6NXl2UWdGQWdNQkFBR2pVekJSTUIwR0ExVWQKRGdRV0JCUVJ3bmdpdElHYkJ1UjBodzZBZHVNTEMyZ1liVEFmQmdOVkhTTUVHREFXZ0JRUnduZ2l0SUdiQnVSMApodzZBZHVNTEMyZ1liVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFPCkMxOHMxdlBocndXa1p0K29uTEJkR1h2RloxNG16cTdnMElreGljcVd5QUVUUXQwVXdsSWtLSGVPaDZPNDdyTzEKR25PYzl1M09KMmtQRE5weVJMLytURktUajlwRVBHZUs0WGQ2NTRta01TNitNMUF6R2hLUFA0d09QRy9CcENVUgo3NnVPcVZIL0hoNmUxMXF1d3dzbEt3TTdRN0FIb2pJeHk1Skl1TFI4NUd2NE14cm1WUmFla3FNYmE3U29Ja213CkJQWDN1bzNhdkh3WWYycnRTMit0WFA0dWFNOW96c1ZVWXhFZ0N6elVtN0hiN3h0R1FLREROT3FWSEsxS3J3dU4KUHF5V3pmY3ZtUFc2T1lhOGVTYmU4T3RsalRXU0IxSk5hUVplMHN4cTB5T0JOVnVnYVlObEFDRWtjREpTbW9ZUQp6c3pyUmtOZXp3UU01aERWZ0R0RgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2d4VG9xV0dhY2VVTWkKNDdPY1l5SDJrYUd1L1VHTE1QYld6RWJhSW9qNUlmaGxobmZ5YmR0M0dWMzEyaDNmdEt0aEtQLzBzY2F5bUw2Rgo1UlQ4OTRIelEyTUdpZ2NoSnNsTGNtNUNiWXJ6anAzbEJrRVB1N3ljQnFwSytYQ055a3RDbkFjcW1PQU10ckNxCkR6Mk50OVdUc0JRQnhFL01PbmlqL2hzeS9aUXo3bUlXYVRzZC9GY2E3azFqSjBSL2NoQmtLdXM3M2lYejVON3AKSjF3UzZiNE0zRWltRlJVcFMrRndndGxjc3JuY3J0NzNGUnBXcWZxbU1hUjBTaWc1SW9LMUdBdjdsUW9Lb2ZFLwpodEk4SmNZekJvbHhFY2c3YitiaTd5TDBaTmc0NHorYzVUYjZ5aUROZlRCbU83N0FMVHJha1pyOG5UdS8zR0pMCnF6NXl2UWdGQWdNQkFBRUNnZ0VBSFYzSlVTRFNwWFJVK2hPRHBHWkxOdUhGR2RTeTJ6ejNhYWJvcmtHdXFXczIKRnoxbnZZV3BsK2l2VEJBcWNzbHFvSlcvb3kreDdyK04xYUZSb3grR3dpdWw4L1RVZG83Q0tDRGYyUXh2WEN2SgoxYUs5MGFUbVA4M0wzMlFPMWllRWRjZFFXOHlPNkdPYWc0WERKWmJWMFdOUlZEMUtvakJ3QnV5TWhWVGlkRldsCmprak05ZnZQeHdGWEt2NDgrRW5IdkhrK0JFOGJrQVZCKzJSZjlDci9uSEN4QkhiN1ExV2NySTM4NlNiUVpDem8KcDRTN09hMHYrNjN2TGZuRVZIQ0RUWW0vRUp6cEpZZWsvQjFEU2txYnpqL1o5WUxweUJ6RXZUNWFNMmtnRlovVQpvZlNCQjZIb1Y0WXN0c3RGWEVIWmZSUDY0SDkvYUxtMWZvT1E1Q1B3QVFLQmdRRGFZTTJMSjZ5RnR5UmVxYmxRCjcwZDJ1TERaMFdxZHYzTU95NC9iUUxzZ3F1YXcvWGQ4NnNxd2ZoV2IzZ09iSTFTT29SeXAyTWx4MTdOckl6eUEKV25mRUlwaUcwYmtDVHpDMHNTd091V2I0NURwaTlIOFRZakljTi9JcVc1dFNiWkNzRVBRYVF3ekkvMmtZVGtLeQpvd1k3UlFSeG91dGp2a1ZnNnhKZ1B5S2tCUUtCZ1FDOGQ3dlM0M1Iva3h4L0VPZ3E1WFNIR2lxRzFFTDlwZ3V0CmxoYTNHeUNjd011Z0QwT0JaZkQ0Y2JleFlKUncrSlQwaFZSOGFuTmZCZXkrb2ZteWJmaW4wVWlSdFhZZFIyUHMKajFVODI5dmN0VUtwWUdQdVg2MWNSem1oZ0MvOU1TNWpMYWNEY0E3eTRUL3pIcCs0QkVidWY4VjltTnVuU1ZBTAprcjVqMThJVUFRS0JnQWNoZWhTOUt1a0MzZkVwWVorKzhIcHo5WEpuWUMvZWZJZFRKbE5tZmJYSFh0a1FyY0lxCmVJdmkwaG5RMmhWS3hnd1NQcmxkRnRiYzBFTURWNHBwYWRmQnVYRk5qOWovZFB1eGZWck51d3NOaU1xS2FVdmMKdlA0bTVZVjBrRkhVdWhDa1RSUStkRUJyOXFhUWg2VUZwY0p4c245emJuUkhWa1NmNkcyMEloRnhBb0dBYWU1UwpuOEpBNU1QbkxIUndTa3dXSnluSjVXYkJFSmlYejhXZ2x1S2tmZmJQZlBPWFdjL1dsWTQxVlhtWGRiZ0M0VDFmCnMxNlI0a01PUWtnQWRRM2l5VkNVblhHRkpnZk9YbFJoOEljVEdRYTRwVU1NYUJ0Vzhac0hCWU5yZGNDQzlqUGUKdjh2b1d4UElRZnBnZzZuRHhLSUVld2ZEems4aXNwNlViTUlFMEFFQ2dZRUFzV2tTTVlNUks5dkkrSVEyaTVaQgpFbFNCaWlIbnlXWTNuZXlROFM5ZzdxUkdqM2dPekRscEZLUHowTUNJbnhDTkxLaFlCTGI3WDFKdlhlNHdkQWhOCnRKb3hHeVhuRUdvMHhwMWRQeForTmpJZGV5OUhTcEl1TGVydEZNY3BHQlhQS1AxTW9vdXVKQVg2eXdMVlZ2OVkKckdXWjY4N3BmVHdFUGdKWVQ3akFOTkE9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-tls
              mountPath: "/certs"
              readOnly: true
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
      volumes:
        - name: registry-tls
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000