apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  containers:
  - name: gpu-test-container
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    resources:
      limits:
        nvidia.com/gpu: 1  # Requests one GPU (adjust if needed)
    command: ["bash", "-c", "sleep infinity"]
  restartPolicy: Never
