apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-job-api
  template:
    metadata:
      labels:
        app: k8s-job-api
    spec:
      containers:
      - name: k8s-job-api
        image: cluster_proxy:latest
        imagePullPolicy: Never  # Ensure Kubernetes uses the local image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: shared-volume
          mountPath: /mnt
      serviceAccountName: k8s-job-api-sa
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: example-pvc