apiVersion: batch/v1
kind: Job
metadata:
  name: list-pv-contents-job
spec:
  template:
    spec:
      containers:
      - name: list-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["ls -R /mnt/data && echo 'Current working directory:' && pwd"]
        volumeMounts:
        - name: shared-volume
          mountPath: /mnt/data
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: example-pvc