# registry-nodeport-service.yaml
# this is for external access

apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: default
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
  type: NodePort
