apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Ensure this path is correct
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Add this line if you want to specify a storage class