   apiVersion: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   metadata:
     name: job-creator-binding
     namespace: default
   subjects:
   - kind: ServiceAccount
     name: k8s-job-api-sa
     namespace: default
   roleRef:
     kind: Role
     name: job-creator
     apiGroup: rbac.authorization.k8s.io